from bot import CMD_INDEX


class _BotCommands:
    def __init__(self):
        self.StartCommand = f'srt{CMD_INDEX}'
        self.MirrorCommand = f'mir{CMD_INDEX}'
        self.UnzipMirrorCommand = f'unzipmirr{CMD_INDEX}'
        self.ZipMirrorCommand = f'zipmirr{CMD_INDEX}'
        self.CancelMirror = f'can{CMD_INDEX}'
        self.CancelAllCommand = f'canall{CMD_INDEX}'
        self.ListCommand = f'l{CMD_INDEX}'
        self.SearchCommand = f's{CMD_INDEX}'
        self.StatusCommand = f'ustatus{CMD_INDEX}'
        self.AuthorizedUsersCommand = f'users{CMD_INDEX}'
        self.AuthorizeCommand = f'auth{CMD_INDEX}'
        self.UnAuthorizeCommand = f'unaut{CMD_INDEX}'
        self.AddSudoCommand = f'asudo{CMD_INDEX}'
        self.RmSudoCommand = f'rsudo{CMD_INDEX}'
        self.PingCommand = f'p{CMD_INDEX}'
        self.RestartCommand = f're{CMD_INDEX}'
        self.StatsCommand = f'stat{CMD_INDEX}'
        self.HelpCommand = f'h{CMD_INDEX}'
        self.LogCommand = f'l{CMD_INDEX}'
        self.CloneCommand = f'copy{CMD_INDEX}'
        self.CountCommand = f'counting{CMD_INDEX}'
        self.WatchCommand = f'w{CMD_INDEX}'
        self.ZipWatchCommand = f'zipw{CMD_INDEX}'
        self.QbMirrorCommand = f'qbmirr{CMD_INDEX}'
        self.QbUnzipMirrorCommand = f'qbunzipmirr{CMD_INDEX}'
        self.QbZipMirrorCommand = f'qbzipmirr{CMD_INDEX}'
        self.DeleteCommand = f'delete{CMD_INDEX}'
        self.ShellCommand = f'shell{CMD_INDEX}'
        self.ExecHelpCommand = f'exechelp{CMD_INDEX}'
        self.LeechSetCommand = f'leechsetting{CMD_INDEX}'
        self.SetThumbCommand = f'setthumbnail{CMD_INDEX}'
        self.LeechCommand = f'leeching{CMD_INDEX}'
        self.UnzipLeechCommand = f'unzipleeching{CMD_INDEX}'
        self.ZipLeechCommand = f'zipleeching{CMD_INDEX}'
        self.QbLeechCommand = f'qbleeching{CMD_INDEX}'
        self.QbUnzipLeechCommand = f'qbunzipleeching{CMD_INDEX}'
        self.QbZipLeechCommand = f'qbzipleeching{CMD_INDEX}'
        self.LeechWatchCommand = f'leechw{CMD_INDEX}'
        self.LeechZipWatchCommand = f'leechzipw{CMD_INDEX}'
        self.RssListCommand = f'rsslist{CMD_INDEX}'
        self.RssGetCommand = f'rssget{CMD_INDEX}'
        self.RssSubCommand = f'rsssub{CMD_INDEX}'
        self.RssUnSubCommand = f'rssunsub{CMD_INDEX}'
        self.RssSettingsCommand = f'rssset{CMD_INDEX}'
        self.EvalCommand = f'eval{CMD_INDEX}'
        self.ExecCommand = f'exec{CMD_INDEX}'
        self.ClearLocalsCommand = f'clearlocals{CMD_INDEX}'

BotCommands = _BotCommands()
